name: Build and Push Docker Image

on:
  # 手动触发
  workflow_dispatch:
  # 每周一早上 7:00 (UTC+8 中国时间)
  schedule:
    - cron: '0 23 * * 0' # GitHub Actions 使用 UTC 时间，这里是周日 23:00 UTC == 周一 07:00 CST

permissions:
  contents: read
  packages: write  # 推送镜像到 GHCR
  id-token: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workflow Repo
        uses: actions/checkout@v4

      - name: Checkout Joplin Source
        uses: actions/checkout@v4
        with:
          repository: 'laurent22/joplin'
          ref: dev
          path: joplin

      ## 修复标题框输入乱跳的问题
      - name: Patch TextInput to fix input jumping
        run: bash patch-textinput.sh

      - name: Prepare yarn
        run: corepack enable

      - name: Install Joplin dependencies
        working-directory: ./joplin
        run: yarn install

      - name: Build Joplin Web
        working-directory: ./joplin/packages/app-mobile
        run: yarn web

      # ⭐ 新增：修复 pages 目录缺失问题
      - name: Create pages directory and copy Joplin artifact
        run: |
          mkdir -p pages/
          cp -r joplin/packages/app-mobile/web/dist/* pages/

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "tag=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      # 新增：预先计算全小写的镜像名
      - name: Compute lowercase image name
        id: prep
        shell: bash
        run: |
          # 确保镜像名格式正确：ghcr.io/用户名/镜像名
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/joplin-web-app"
          echo "image=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ⭐ 新增：明确指定 Dockerfile 路径
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # 明确指定 Dockerfile 路径
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:latest
            ${{ steps.prep.outputs.image }}:${{ steps.vars.outputs.tag }}

      # ⭐ 新增：验证镜像推送成功
      - name: Verify image push
        run: |
          echo "验证镜像是否成功推送:"
          echo "镜像: ${{ steps.prep.outputs.image }}"
          echo "标签: ${{ steps.vars.outputs.tag }}"

  cleanup_old_images:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Delete old container images (keep latest 5)
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 5
